kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prom-rlw-binding
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prom-rlw
  apiGroup: rbac.authorization.k8s.io
