apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  initContainers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  containers:
  - name: web
    image: ruwoyager/k8s-intro-web:latest
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
